<a href="https://colab.research.google.com/github/ritzx21/Titanic-ML-prediction-Kaggle-/blob/main/Titanic_Kaggle_ML_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

import tensorflow as tf

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/ritzx21/Titanic-ML-prediction-Kaggle-/main/Titanic%20Dataset%20(Kaggle%20competition)/train.csv")

In [3]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

1 - passenger survived

2 - passenger died

In [4]:
df.shape

(891, 12)

In [5]:
df['Embarked'].value_counts()

S    644
C    168
Q     77
Name: Embarked, dtype: int64

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [7]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [8]:
df['Cabin'].value_counts()

B96 B98        4
G6             4
C23 C25 C27    4
C22 C26        3
F33            3
              ..
E34            1
C7             1
C54            1
E36            1
C148           1
Name: Cabin, Length: 147, dtype: int64

In [9]:
df['Cabin'] = df['Cabin'].fillna(" ")

In [10]:
df.Age = df.Age.fillna(df.Age.mean())

In [11]:
df['Embarked'] = df['Embarked'].fillna(" ")

In [12]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [13]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,,S

In [14]:
women = df.loc[df.Sex == 'female']["Survived"]
percent_women = sum(women)/len(women)

print(f"% of women survived is {percent_women*100}")

% of women survived is 74.20382165605095

In [19]:
men = df.loc[df.Sex == 'male']['Survived']
percent_men = sum(men)/len(men)

print(f"% of men survived is {percent_men*100}")

% of men survived is 18.890814558058924

In [55]:
cols = ['Pclass','Sex','Age','Parch','SibSp']
X_train = pd.get_dummies(df[cols])

In [56]:
Y_train = df['Survived']

In [57]:
test_df = pd.read_csv("https://raw.githubusercontent.com/ritzx21/Titanic-ML-prediction-Kaggle-/main/Titanic%20Dataset%20(Kaggle%20competition)/test.csv")

In [58]:
test_df.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [59]:
df.shape

(891, 12)

In [60]:
test_df.shape

(418, 11)

In [61]:
test_df.isnull().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [62]:
test_df.Age = test_df.Age.fillna(test_df.Age.mean())

In [63]:
test_df['Cabin'] = test_df['Cabin'].fillna(" ")

In [64]:
test_df.Fare = test_df.Fare.fillna(test_df.Fare.mean())

In [65]:
test_df.isnull().sum()

PassengerId    0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [67]:
test_cols = ['Pclass','Sex','Age','Parch','SibSp']
X_test = pd.get_dummies(test_df[test_cols])

In [68]:
X_test

     Pclass       Age  Parch  SibSp  Sex_female  Sex_male
0         3  34.50000      0      0           0         1
1         3  47.00000      0      1           1         0
2         2  62.00000      0      0           0         1
3         3  27.00000      0      0           0         1
4         3  22.00000      1      1           1         0
..      ...       ...    ...    ...         ...       ...
413       3  30.27259      0      0           0         1
414       1  39.00000      0      0           1         0
415       3  38.50000      0      0           0         1
416       3  30.27259      0      0           0         1
417       3  30.27259      1      1           0         1

[418 rows x 6 columns]

In [69]:
from sklearn.ensemble import RandomForestClassifier

In [70]:
model = RandomForestClassifier()

In [71]:
model.fit(X_train , Y_train)

RandomForestClassifier()

In [72]:
Y_predict = model.predict(X_test)

In [73]:
Y_predict.shape

(418,)

In [74]:
output = pd.DataFrame({'PassengerId': test_df.PassengerId, 'Survived': Y_predict})
output.to_csv('Submission.csv', index=False)
print("Saved")

Saved